### ISSUE TITLE
Ensure that product sync/differ create only one update action for setAttributeInAllVariants

### ISSUE THREAD

**Issue by butenkor** [sphereio/sphere-node-sdk#81]
If product has 5 variants with attribute ```brand``` and brand has been changed in all variants from ```A``` to ```B``` then product-sync will generate 5 update actions of type ```setAttributeInAllVariants```. It should generate only one update action per product and attribute flaged as ```sameForAll```.

**Comment by emmenko** [comment]
Sounds good :+1: 

Can you make a PR?

**Comment by panshul007** [comment]
:+1: would be nice to get a PR :+1:

**Comment by hajoeichler** [comment]
@butenkor please provide a test case first - as this feature should be working already!
https://github.com/sphereio/sphere-node-sdk/blob/master/src/spec/sync/utils/product.spec.coffee#L870

**Comment by butenkor** [comment]
@hajoeichler Yes test seems to be correct. @panshul007 Can you still reproduce this issue?

**Comment by emmenko** [comment]
Is this still a problem?

**Comment by butenkor** [comment]
@panshul007 This question is for you.
 Next time create issues yourself ;)
